# This is a simple example of using a config map to create a single page static site.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.frontend.name }}-special-config-frontend
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "mytest.name" . }}
data:
  # When the config map is mounted as a volume, these will be created as files.
  config.json: |
    {
      "backend": "{{ include "mytest.fullname" . }}",
      "backendPort": {{ index .Values "service" "port" | quote }}
    }
