# This is a simple example of using a config map to create a single page static site.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mytest.fullname" . }}-special-config-backend
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "mytest.name" . }}
data:
  # When the config map is mounted as a volume, these will be created as files.
  config.toml: |
    [alias]
    redis={{ .Release.Name }}-redis-ha:{{ index .Values "redis-ha" "redis" "port" }}
    cockroach={{ .Release.Name }}-cockroachdb:{{ index .Values "cockroachdb" "ExternalGrpcPort" }}
